// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UNIVidaPortalWeb.Convocatorias.Repositories;

#nullable disable

namespace UNIVidaPortalWeb.Convocatorias.Migrations
{
    [DbContext(typeof(DbContextConvocatorias))]
    [Migration("20241104164217_InicioMigracionCorreccion2")]
    partial class InicioMigracionCorreccion2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Convocatoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParEstadoConvocatoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeMinimo")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeTotal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParEstadoConvocatoriaId");

                    b.ToTable("Convocatoria", "Convocatorias");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<int>("PostulacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostulacionId");

                    b.ToTable("Notificacion", "Convocatorias");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Postulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvocatoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<int>("ParEstadoPostulacionId")
                        .HasColumnType("integer");

                    b.Property<string>("PostulanteDatosJSON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeObtenido")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvocatoriaId");

                    b.HasIndex("ParEstadoPostulacionId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("Postulacion", "Convocatorias");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParEstadoConvocatoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParEstadoConvocatoria", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParEstadoPostulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoNotificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<bool>("Notificar")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ParEstadoPostulacion", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParIdioma", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParNivelConocimiento", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelFormacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParNivelFormacion", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParParentesco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParParentesco", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParPrograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParPrograma", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParTipoCapacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParTipoCapacitacion", "Parametricas");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Capacitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroEstudios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HorasAcademicas")
                        .HasColumnType("integer");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParTipoCapacitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParTipoCapacitacionId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("Capacitacion", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ConocimientoIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<int>("ParIdiomaId")
                        .HasColumnType("integer");

                    b.Property<int>("ParNivelConocimientoConversacionId")
                        .HasColumnType("integer");

                    b.Property<int>("ParNivelConocimientoEscrituraId")
                        .HasColumnType("integer");

                    b.Property<int>("ParNivelConocimientoLecturaId")
                        .HasColumnType("integer");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParIdiomaId");

                    b.HasIndex("ParNivelConocimientoConversacionId");

                    b.HasIndex("ParNivelConocimientoEscrituraId");

                    b.HasIndex("ParNivelConocimientoLecturaId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("ConocimientoIdioma", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ConocimientoSistemas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<int>("ParNivelConocimientoId")
                        .HasColumnType("integer");

                    b.Property<int>("ParProgramaId")
                        .HasColumnType("integer");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParNivelConocimientoId");

                    b.HasIndex("ParProgramaId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("ConocimientoSistemas", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.FormacionAcademica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroEstudios")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaTitulo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParNivelFormacionId")
                        .HasColumnType("integer");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.Property<string>("TituloObtenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParNivelFormacionId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("FormacionAcademica", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CiudadNacimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CiudadResidencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoExpedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisNacimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaisResidencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoMovil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Postulante", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ReferenciaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Relacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoMovil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PostulanteId");

                    b.ToTable("ReferenciaLaboral", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ReferenciaPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParParentescoId")
                        .HasColumnType("integer");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoMovil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParParentescoId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("ReferenciaPersonal", "Postulantes");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Convocatoria", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParEstadoConvocatoria", "ParEstadoConvocatoria")
                        .WithMany()
                        .HasForeignKey("ParEstadoConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParEstadoConvocatoria");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Notificacion", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Postulacion", "Postulacion")
                        .WithMany("Notificaciones")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulacion");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Postulacion", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Convocatoria", "Convocatoria")
                        .WithMany("Postulaciones")
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParEstadoPostulacion", "ParEstadoPostulacion")
                        .WithMany()
                        .HasForeignKey("ParEstadoPostulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany()
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convocatoria");

                    b.Navigation("ParEstadoPostulacion");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Capacitacion", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParTipoCapacitacion", "ParTipoCapacitacion")
                        .WithMany()
                        .HasForeignKey("ParTipoCapacitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany("Capacitaciones")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParTipoCapacitacion");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ConocimientoIdioma", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParIdioma", "ParIdioma")
                        .WithMany()
                        .HasForeignKey("ParIdiomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelConocimiento", "ParNivelConocimientoConversacion")
                        .WithMany()
                        .HasForeignKey("ParNivelConocimientoConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelConocimiento", "ParNivelConocimientoEscritura")
                        .WithMany()
                        .HasForeignKey("ParNivelConocimientoEscrituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConocimientoIdioma_ParNivelConocimiento_ParNivelConocimien~1");

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelConocimiento", "ParNivelConocimientoLectura")
                        .WithMany()
                        .HasForeignKey("ParNivelConocimientoLecturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConocimientoIdioma_ParNivelConocimiento_ParNivelConocimien~2");

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany("ConocimientosIdiomas")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParIdioma");

                    b.Navigation("ParNivelConocimientoConversacion");

                    b.Navigation("ParNivelConocimientoEscritura");

                    b.Navigation("ParNivelConocimientoLectura");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ConocimientoSistemas", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelConocimiento", "ParNivelConocimiento")
                        .WithMany()
                        .HasForeignKey("ParNivelConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParPrograma", "ParPrograma")
                        .WithMany()
                        .HasForeignKey("ParProgramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany("ConocimientosSistemas")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParNivelConocimiento");

                    b.Navigation("ParPrograma");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.FormacionAcademica", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParNivelFormacion", "ParNivelFormacion")
                        .WithMany()
                        .HasForeignKey("ParNivelFormacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany("FormacionesAcademicas")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParNivelFormacion");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ReferenciaLaboral", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany("ReferenciasLaborales")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.ReferenciaPersonal", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.ParametricasModel.ParParentesco", "ParParentesco")
                        .WithMany()
                        .HasForeignKey("ParParentescoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", "Postulante")
                        .WithMany("ReferenciasPersonales")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParParentesco");

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Convocatoria", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.ConvocatoriasModel.Postulacion", b =>
                {
                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Convocatorias.Models.PostulantesModel.Postulante", b =>
                {
                    b.Navigation("Capacitaciones");

                    b.Navigation("ConocimientosIdiomas");

                    b.Navigation("ConocimientosSistemas");

                    b.Navigation("FormacionesAcademicas");

                    b.Navigation("ReferenciasLaborales");

                    b.Navigation("ReferenciasPersonales");
                });
#pragma warning restore 612, 618
        }
    }
}
