// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UNIVidaPortalWeb.Cms.Repositories;

#nullable disable

namespace UNIVidaPortalWeb.Cms.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    [Migration("20240605105435_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.BannerPaginaDinamica", b =>
                {
                    b.Property<int>("BannerPaginaDinamicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BannerPaginaDinamicaId"));

                    b.Property<int>("PaginaDinamicaId")
                        .HasColumnType("integer");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.HasKey("BannerPaginaDinamicaId");

                    b.HasIndex("PaginaDinamicaId");

                    b.HasIndex("RecursoId");

                    b.ToTable("BannerPaginaDinamica", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.CatTipoRecurso", b =>
                {
                    b.Property<int>("CatTipoRecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatTipoRecursoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CatTipoRecursoId");

                    b.ToTable("CatTipoRecurso", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.CatTipoSeccion", b =>
                {
                    b.Property<int>("CatTipoSeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatTipoSeccionId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CatTipoSeccionId");

                    b.ToTable("CatTipoSeccion", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.Dato", b =>
                {
                    b.Property<int>("DatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DatoId"));

                    b.Property<int>("Columna")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatoFechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatoTexto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Fila")
                        .HasColumnType("integer");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.HasKey("DatoId");

                    b.HasIndex("RecursoId");

                    b.HasIndex("SeccionId");

                    b.ToTable("Datos", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.PaginaDinamica", b =>
                {
                    b.Property<int>("PaginaDinamicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaginaDinamicaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaginaDinamicaId");

                    b.ToTable("PaginasDinamicas", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.Recurso", b =>
                {
                    b.Property<int>("RecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecursoId"));

                    b.Property<int>("CatTipoRecursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecursoEscritorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecursoMovil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecursoId");

                    b.HasIndex("CatTipoRecursoId");

                    b.ToTable("Recursos", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.Seccion", b =>
                {
                    b.Property<int>("SeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeccionId"));

                    b.Property<int>("CatTipoSeccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PaginaDinamicaId")
                        .HasColumnType("integer");

                    b.Property<string>("SubTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SeccionId");

                    b.HasIndex("CatTipoSeccionId");

                    b.HasIndex("PaginaDinamicaId");

                    b.ToTable("Secciones", (string)null);
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.BannerPaginaDinamica", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Model.PaginaDinamica", "PaginaDinamica")
                        .WithMany()
                        .HasForeignKey("PaginaDinamicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Cms.Model.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaginaDinamica");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.Dato", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Model.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Cms.Model.Seccion", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.Recurso", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Model.CatTipoRecurso", "CatTipoRecurso")
                        .WithMany()
                        .HasForeignKey("CatTipoRecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatTipoRecurso");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Model.Seccion", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Model.CatTipoSeccion", "CatTipoSeccion")
                        .WithMany()
                        .HasForeignKey("CatTipoSeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Cms.Model.PaginaDinamica", "PaginaDinamica")
                        .WithMany()
                        .HasForeignKey("PaginaDinamicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatTipoSeccion");

                    b.Navigation("PaginaDinamica");
                });
#pragma warning restore 612, 618
        }
    }
}
