// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UNIVidaPortalWeb.Cms.Repositories;

#nullable disable

namespace UNIVidaPortalWeb.Cms.Migrations
{
    [DbContext(typeof(DbContextCms))]
    [Migration("20240620222712_campo-tiposeguro")]
    partial class campotiposeguro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.CatalogoModel.CatTipoRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CatTipoRecurso", "Catalogo");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.CatalogoModel.CatTipoSeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CatTipoSeccion", "Catalogo");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.CatalogoModel.CatTipoSeguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CatTipoSeguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.Dato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Columna")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatoFechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatoTexto")
                        .HasColumnType("text");

                    b.Property<string>("DatoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Fila")
                        .HasColumnType("integer");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("SeccionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("SeccionId");

                    b.ToTable("Datos", "PaginaDinamica");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.PaginaDinamica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("PaginasDinamicas", "PaginaDinamica");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.Seccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatTipoSeccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Clase")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PaginaDinamicaId")
                        .HasColumnType("integer");

                    b.Property<string>("SubTitulo")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoSeccionId");

                    b.HasIndex("PaginaDinamicaId");

                    b.ToTable("Secciones", "PaginaDinamica");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.RecursoModel.BannerPagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaginaDinamicaId")
                        .HasColumnType("integer");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeguroId")
                        .HasColumnType("integer");

                    b.Property<string>("SubTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaginaDinamicaId");

                    b.HasIndex("RecursoId");

                    b.HasIndex("SeguroId");

                    b.ToTable("BannerPagina", "Recurso");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.RecursoModel.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CatTipoRecursoId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecursoEscritorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecursoMovil")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoRecursoId");

                    b.ToTable("Recursos", "Recurso");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cobertura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int>("SeguroId")
                        .HasColumnType("integer");

                    b.Property<string>("SubTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("Planes", "Seguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.Seguro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CatTipoSeguroId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetalleAdicional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int?>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.ToTable("Seguros", "Seguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.SeguroDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeguroId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeguroId");

                    b.ToTable("SeguroDetalles", "Seguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.Dato", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.RecursoModel.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId");

                    b.HasOne("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.Seccion", "Seccion")
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.Seccion", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.CatalogoModel.CatTipoSeccion", "CatTipoSeccion")
                        .WithMany()
                        .HasForeignKey("CatTipoSeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.PaginaDinamica", "PaginaDinamica")
                        .WithMany()
                        .HasForeignKey("PaginaDinamicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatTipoSeccion");

                    b.Navigation("PaginaDinamica");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.RecursoModel.BannerPagina", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.PaginaDinamicaModel.PaginaDinamica", "PaginaDinamica")
                        .WithMany()
                        .HasForeignKey("PaginaDinamicaId");

                    b.HasOne("UNIVidaPortalWeb.Cms.Models.RecursoModel.Recurso", "Recurso")
                        .WithMany("BannerPagina")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNIVidaPortalWeb.Cms.Models.SeguroModel.Seguro", "Seguro")
                        .WithMany("BannerPagina")
                        .HasForeignKey("SeguroId");

                    b.Navigation("PaginaDinamica");

                    b.Navigation("Recurso");

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.RecursoModel.Recurso", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.CatalogoModel.CatTipoRecurso", "CatTipoRecurso")
                        .WithMany()
                        .HasForeignKey("CatTipoRecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatTipoRecurso");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.Plan", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.SeguroModel.Seguro", "Seguro")
                        .WithMany("Planes")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.Seguro", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.RecursoModel.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.SeguroDetalle", b =>
                {
                    b.HasOne("UNIVidaPortalWeb.Cms.Models.SeguroModel.Seguro", "Seguro")
                        .WithMany("SeguroDetalles")
                        .HasForeignKey("SeguroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguro");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.RecursoModel.Recurso", b =>
                {
                    b.Navigation("BannerPagina");
                });

            modelBuilder.Entity("UNIVidaPortalWeb.Cms.Models.SeguroModel.Seguro", b =>
                {
                    b.Navigation("BannerPagina");

                    b.Navigation("Planes");

                    b.Navigation("SeguroDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
